services:
  app:
    container_name: training_go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file:
      - ./cloud/docker/development.env
    networks:
      - go-network

  mysql:
      container_name: bjjsystem_mysql
      image: mysql:8.0
      volumes:
        - mysql:/var/lib/mysql
      env_file:
        - ./cloud/docker/development.mysql.env
      ports:
        - 3306:3306
      networks:
        - go-network

networks:
  go-network:
    driver: bridge
volumes:
  mysql:
